version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5430:5432"
    environment:
      - "POSTGRES_DB=bot"
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=root"
    volumes:
      - postg:/var/lib/postg

volumes:
  postg: