spring:
  application:
    name: learn-bot

  datasource:
    url: jdbc:postgresql://localhost:5430/bot
    password: root
    driver-class-name: org.postgresql.Driver
    username: root

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


bot:
  token: 7623653553:AAGe4RCDWE4MCI2Fy2jnuqJ4gvEZA521NvU